### ISSUE TITLE
Update for Azuriom v1.0

### ISSUE THREAD

**Issue by TzunamiDev** [Javdu10/Game-Dofus129#1]
![image](https://user-images.githubusercontent.com/37744155/171513658-a7b74c27-d228-4614-8b9e-4d7242efea67.png)

Game does not appear in Azuriom installation:
![image](https://user-images.githubusercontent.com/37744155/171513842-9a9f27a6-65e1-4878-9d0f-cb4dec60f332.png)

**Comment by Javdu10** [comment]
should be fixed with 5336dd469b660838b63fc0c30dbb0ba38c84fdae now waiting approval on the market
