### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by p2635** [Javdu10/Game-Dofus129#2]
It's my first time setting this up, but I don't know what table definitions should be for the database (data types etc). I am just guessing my way through, do you have a script or something to create all the tables?

**Comment by Javdu10** [comment]
Well the installation is the script...
All you have to do is give it column names that your emulator is using

**Comment by p2635** [comment]
I ended up guessing what they are, I don't know what would be a varchar or an int. There was a column called 'pseudo' for example and I had no idea what that is.

Also, do you know how I can get Dofus 1.29 client? I found some on the net but didn't know how to configure it to connect to my own server.

**Comment by Javdu10** [comment]
You don't have to guess anything. The columns should come from a working emulator. 

I don't have a 1.29 client nor tutorial myself but you'll find plenty of resources in specific forums.

Just to make sure, this plugin is not an emulator! 

It's only used for displaying data like ladders, characters informations etc, and to send commands to the emulator that can give items/points to players when they buy/vote on the website.

**Comment by p2635** [comment]
Thanks for clarifying, I got too excited. I will just delete it then. It will take me more effort to browse forums to track it down.
